### ISSUE TITLE
Prebuilt executables

### ISSUE THREAD

**Issue by airD173** [daspartho/SpotiByeAds#42]
I think we should make a separate thread since this is a common request. We have a way to use py2app for Mac, but my attempts with pyinstaller and cxfreeze on windows have been unsuccessful. Has anyone else built outside of Mac?

**Comment by AnonymouX47** [comment]
At the moment, I'm not sure how workable this is for Windows.

I tried PyInstaller with no success... i'll elaborate more soon.

I think the best option for now is for the user to have python installed, install the dependencies and run the script directly.

**Comment by airD173** [comment]
Have you been getting the same error as I have? I was getting import errors so it kept trying to download off of requirements.txt (which didn't exist in the build directory). Once I added requirements.txt, it downloaded, but still had an import error. Commenting out the code that downloads just showed an import error again. Switching from pyinstaller to cxfreeze did nothing.

I too believe it's easy to install with Python, but prebuilt executables are even easier.

**Comment by AnonymouX47** [comment]
I tried PyInstaller (using the `--onefile` option) and encountered an `ImportError`.
I should note that the 3rd-party libraries were also packaged along.

The import error occured from the `pynput` library:
```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from pynput.keyboard import Key, Controller
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "pynput\__init__.py", line 40, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "pynput\keyboard\__init__.py", line 31, in <module>
  File "pynput\_util\__init__.py", line 82, in backend
ImportError
[5644] Failed to execute script main
```

I went on to inspect the `backend()` function in "pynput\_util\__init__.py".
The error seems to be caused by an "hidden" import on line 70:
```python
importlib.import_module('._' + module, package)
```
and according to PyInstaller's docs [here](https://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html#listing-hidden-imports):
> Hidden imports can occur when the code is using `__import__()`, `importlib.import_module()` or perhaps `exec()` or `eval()`. Hidden imports can also occur when an extension module uses the Python/C API to do an import. When this occurs, Analysis can detect nothing. There will be no warnings, only an ImportError at run-time.

From what i understand from the code in `backend()`, it's trying to load some moudle(s) for platform-dependent back-end support.

**Comment by AnonymouX47** [comment]
I just found a fix, adding `--collect-submodules pynput` to the build command ensures the module being imported is also bundled. Thereby fixing the issue.

**Comment by airD173** [comment]
Strange, it successfully built just a couple of minutes ago (with collect submodules), but I tried doing it in WSL and it's getting an import error. I go back to windows to find that it's now also giving an importerror. I'll clone from scratch and try again.

**Comment by AnonymouX47** [comment]
@daspartho What say you?

**Comment by airD173** [comment]
Alright, it magically fixed itself. Anyways, that's good news. We can now have prebuilt releases.

**Comment by AnonymouX47** [comment]
>  but I tried doing it in WSL

WSL is a linux subsystem, not windows.

I'll try it on linux and see how it goes... though, i think running the script directly is still better since most recent linux systems come with Python 3.

**Comment by airD173** [comment]
I do agree with you on that. There's also the fact that

**Comment by airD173** [comment]
I did not mean to close

**Comment by airD173** [comment]
> > but I tried doing it in WSL
> 
> WSL is a linux subsystem, not windows.
> 
> I'll try it on linux and see how it goes... though, i think running the script directly is still better since most recent linux systems come with Python 3.

I'm well aware of that, I was testing if it worked on Linux but didn't feel like rebooting to get into actual Ubuntu.

**Comment by AnonymouX47** [comment]
> I do agree with you on that. I also believe anyone willing to use Linux is probably tech savvy enough to install pip and dependencies. Still, prebuilt releases are always nice.

True, but it won't cost anything much to add for linux also.

**Comment by AnonymouX47** [comment]
> I'm well aware of that, I was testing if it worked on Linux but didn't feel like rebooting to get into actual Ubuntu.

Oh I see.

**Comment by AnonymouX47** [comment]
I just tested it on linux also, works totally fine.
I used this line on both Linux and Windows:
```
pyinstaller --onefile --hidden-import spotipy --collect-submodules pynput main.py
```
My only issue is with the sizes of the executables... i think downloading about 10mb for every update of the script would be worse than just downloading python and the dependencies once and updating the script.

**Comment by AnonymouX47** [comment]
The following issues will be introduced by adding standalone executables:
1. Inconsistency in path for credentials store, this applies when the program is executed from a CLI.
2. How will updates be handled?

The way i see it, maybe only this will only be done for Windows and MacOS. I said so because most linux users will generally start the program from a shell and not a file manager.

Elaborating on point 1, it's due to the fact that CWD will probably not be the same as the executable's location.

**Comment by AnonymouX47** [comment]
> 1. Inconsistency in path for credentials store, this applies when the program is executed from a CLI.

This can be fixed for the file directly written/read by the script but i wonder how it'll be done for the username cache used by the Spotify API.

**Comment by import-brain** [comment]
It seems like PyInstaller allows use of the "--collect-all" argument for dependencies when calling it from the command line. I just used py -m PyInstaller main.py -F --collect-all spotipy --collect-all pynput --collect-all py2app and it worked (See pull request #69).

I tried running it on a computer that doesn't even have Python installed, and it worked just fine.

**Comment by AnonymouX47** [comment]
I think `--collect-all` option is unnecessary, just increases the executable size... I built it using the line in the README (which I added after testing) and it worked fine on Windows and Linux (and supposedly Mac OS, though I've not yet tested it).

**Comment by import-brain** [comment]
> 
> 
> I think `--collect-all` option is unnecessary, just increases the executable size... I built it using the line in the README (which I added after testing) and it worked fine on Windows and Linux (and supposedly Mac OS, though I've not yet tested it).
> 
> Also, what's `py2app` doing there?

Whenever I ran the exe, it would throw the import error without everything in the requirements.txt
